const list = [
  {
    id: 1,
    title: "Peanut Butter Chocolate Chip (2.4 Ounce Bars, 12 Count)",
    price: 29.88,
    img: "https://m.media-amazon.com/images/I/51ukLlf5Z1L._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Sport Whey Protein Powder Vanilla",
    price: 41.44,
    img: "https://m.media-amazon.com/images/I/71xqnuQ5JNL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Women’s Prenatal Multivitamin with Vitamin D3, B6, B12, C & Iron",
    price: 32.94,
    img: "https://m.media-amazon.com/images/I/91-at+aiMGL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Electrolyte Powder Packets - Grape, Fruit Punch, Strawberry Lemonade, Cherry - 32 Count",
    price: 35.99,
    img: "https://m.media-amazon.com/images/I/81v7ohlhr+L._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "BALA Enzyme Electrolyte Powder Packets",
    price: 44.99,
    img: "https://m.media-amazon.com/images/I/81+JtpTrSuL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Flat Tummy Meal Replacement Shake",
    price: 63.99,
    img: "https://m.media-amazon.com/images/I/41y+vEQCViL._AC._SR360,460.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Whey Chocolate Isolate Protein Powder",
    price: 64.22,
    img: "https://m.media-amazon.com/images/I/415+H5UGpKL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Keto Electrolyte Powder Packets",
    price: 45.00,
    img: "https://m.media-amazon.com/images/I/81dhQeSxIpL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Optimum Nutrition Gold Standard 100% Whey Protein Powder, Double Rich Chocolate, 5 Pound (Packaging May Vary)",
    price: 80.95,
    img: "https://m.media-amazon.com/images/I/61u-qC6Z-mL._AC._SR360,460.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Big 100 Protein Bar, Meal Replacement Bar, 32G Protein, Super Cookie Crunch, 3.52 Oz (Pack of 9)",
    price: 28.63,
    img: "https://m.media-amazon.com/images/I/71VWBOcO7OL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Life Extension Neuro-Mag Magnesium L-Threonate",
    price: 28.44,
    img: "https://m.media-amazon.com/images/I/71adg+PdxYL._AC._SR360,460.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "New KetoLuxe Plus Advanced Apple Cider Maximum Strength Formula",
    price: 29.95,
    img: "https://m.media-amazon.com/images/I/81wtxhYVQTL._AC._SR360,460.jpg",
    amount: 1,
  },
  {
    id: 13,
    title: "vitafusion Womens Multivitamin Gummies",
    price: 29.95,
    img: "https://m.media-amazon.com/images/I/81DJDrx8gRL._AC._SR360,460.jpg",
    amount: 1,
  },
  {
    id: 14,
    title: "Performance Inspired Nutrition PreWorkout Powder - All Natural - G-Free & Vegan Formula",
    price: 52.21,
    img: "https://m.media-amazon.com/images/I/81LXjiiUbnL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 15,
    title: "PureClean Organic Beet Juice Powder - Nitric Oxide Supplement ",
    price: 29.95,
    img: "https://m.media-amazon.com/images/I/71gM3bStw3L._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 16,
    title: "BEET'UMS - Great-Tasting Performance Chews (1-Pack)",
    price: 39.95,
    img: "https://m.media-amazon.com/images/I/716O42ItJkL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 17,
    title: "Proven4 Sport Watermelon Pre Workout Powder for Men and Women with Creatine",
    price: 37.99,
    img: "https://m.media-amazon.com/images/I/61hx7+bynPL._AC_SR480,570_.jpg",
    amount: 1,
  },
  {
    id: 18,
    title: "C4 Sport Pre Workout Powder Blue Raspberry - Pre Workout Energy with 3g Creatine Monohydrate + 135mg",
    price: 19.99,
    img: "https://m.media-amazon.com/images/I/817UWJozaRL._AC._SR360,460.jpg",
    amount: 1,
  },
  {
    id: 19,
    title: "L Arginine Capsules Supplement - 1600mg Nitric Oxide Supplement ",
    price: 16.69,
    img: "https://m.media-amazon.com/images/I/719OpH-sO0L._AC._SR360,460.jpg",
    amount: 1,
  },
  {
    id: 20,
    title: "Sugar Free Beet Root Gummies - Nitric Oxide Beet Chews Infused with Coconut Oil",
    price: 9.97,
    img: "https://m.media-amazon.com/images/I/71ZiMwGwucL._AC._SR360,460.jpg",
    amount: 1,
  },
];

export default list;
